### Working with Numpy - for mathematical operations

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
# Creating an array in numpy
a = np.array([1, 2, 3, 4 , 5])
print(a)
print(type(a))
print(a.shape)  # shape returns a tuple which contains the dimensions of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c[1, 2])

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [6]:
# Create zeros, Ones, Custom array
a = np.zeros((3, 3))
print(a)

b = np.ones((2, 3))
print(b)

# Array of some constants
c = np.full((3, 2), 5)
print(c)

# Identity Matrix - Square Matrix
d = np.eye(4)
print(d)

# Random Matrix
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.5270059  0.30927075 0.56935677]
 [0.55904496 0.04026788 0.16526412]]


In [7]:
# Accessing elements
print(randomMatrix[ : , 1])
print(randomMatrix[ : , 2])
print(randomMatrix[1, : ])

[0.30927075 0.04026788]
[0.56935677 0.16526412]
[0.55904496 0.04026788 0.16526412]


In [8]:
# Updating elements
randomMatrix[1, 1 : ] = 3
print(randomMatrix)

[[0.5270059  0.30927075 0.56935677]
 [0.55904496 3.         3.        ]]


In [9]:
# Set some rows and columns with any values
z = np.zeros((3, 3))
print(z)

z[1, : ] = 4
z[ : , -1] = 6
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 6.]
 [4. 4. 6.]
 [0. 0. 6.]]


In [10]:
# Data types
z = np.zeros((3, 3))
print(z.dtype)

z = np.zeros((3, 3), dtype = np.int64)
print(z.dtype)

float64
int64


In [11]:
# Mathematical Operations

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Element wise addition
print(x + y)
print(np.add(x, y))

# Element wise subtraction
print(x - y)
print(np.subtract(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [12]:
# Element wise multiplication
print(x*y)
print(np.multiply(x, y))

# Element wise division
print(x/y)
print(np.divide(x, y))

print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [13]:
# Matrix multiplication (Dot Products)
print(x)
print(y)

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
# Multiplication(Dot Product) of Vectors is a Scalar
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(a.dot(b))

30


In [15]:
print(a)

[1 2 3 4]


In [16]:
print(sum(a))
print(np.sum(a))

10
10


In [17]:
print(x)

[[1 2]
 [3 4]]


In [18]:
print(np.sum(x))
print(np.sum(x, axis = 0))
print(np.sum(x, axis = 1))

10
[4 6]
[3 7]


In [19]:
### Stacking of arrays
print(a)
b = b*2
b = b**2
print(b)

[1 2 3 4]
[ 4 16 36 64]


In [20]:
np.stack((a, b), axis = 1)

array([[ 1,  4],
       [ 2, 16],
       [ 3, 36],
       [ 4, 64]])

In [21]:
np.stack((a, b), axis = 0)

array([[ 1,  2,  3,  4],
       [ 4, 16, 36, 64]])

In [22]:
# Reshape a numpy array
m = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(m)

n = m.reshape((4, 2))
print(n)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
