### Numpy Random Module
- rand : Return random values in a given shape
- randn : Return a sample (or samples) from the "standard normal" distribution
- randint : Return random integers from low (inclusive) to high (exclusive)
- random : Return random floats in the half-open interval [0.0, 1.0)
- choice : Generates a random sample from a given 1-D array
- shuffle : Shuffles the contents of a sequence

In [1]:
import numpy as np

In [2]:
a = np.arange(10)
print(a)

b = np.arange(10) + 5
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [3]:
np.random.shuffle(a)
print(a)

[4 0 6 9 5 7 8 1 2 3]


In [4]:
c = np.random.rand(2, 3)
print(c)

[[0.00216556 0.94945637 0.82915469]
 [0.59441383 0.45233823 0.24548616]]


In [5]:
# Returns values from a Standard Normal Distribution
d = np.random.randn(2, 3)
print(d)

[[-0.58731215  0.37068864 -0.02047814]
 [ 0.1368515  -0.46276718 -0.76118193]]


In [6]:
# Randomly pick some integers in the given range
x = np.random.randint(5, 10, 3)
print(x)

[7 9 6]


In [7]:
# Randomly pick one element from a array
element = np.random.choice([1, 2, 3, 4, 5])
print(element)

2


In [8]:
z = np.random.random((2, 2))
print(z)

[[0.48945204 0.90465403]
 [0.53602986 0.2300405 ]]
