### Some Numpy Functions - Statistics
- min, max
- mean
- median
- average
- variance
- standard deviation

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [3]:
print(np.min(a))
#Specify axis for the direction in case of multi-dimensional array
print(np.min(a, axis = 0))
print(np.min(a, axis = 1))

0
[1 2 2 0]
[1 0]


In [4]:
print(np.mean(a))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

3.125
[4.  4.  2.5 2. ]
[2.5  3.75]


In [5]:
b = np.array([1, 2, 3, 4, 5])
print(np.mean(b))

3.0


In [6]:
c = np.array([8, 9, 7, 6, 10])
print(np.median(c))

8.0


In [7]:
# Mean vs Average 
# Average is weighted
c = np.array([1, 5, 4, 2, 0])
print(np.mean(c))

w = np.array([1, 2, 3, 4, 5])
print(np.average(c, weights = w))

2.4
2.066666666666667


In [8]:
# Standard deviation
u = np.mean(c)
myStd = np.sqrt(np.mean(abs(c-u)**2))
print(myStd)

# Inbuilt function
dev = np.std(c)
print(dev)

#Variance
print(dev**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
