### Broadcasting
- We can add a scalar to a vector, and numpy will add it to each element in the vector.
- Similarly, we can add a vector to a matrix, and numpy will add the vector to each column of the matrix.

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
print(x)
print(x + 4)

[1 2 3 4]
[5 6 7 8]


In [3]:
y = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(y + x)

[[ 2  4  6  8]
 [ 6  8 10 12]]


### Element wise multiplication - Hadamard Product

In [4]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[0, 2], 
              [3, 2]])

print(a*b)

[[0 4]
 [9 8]]


### Matrix Multiplication - Dot Product

In [5]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[0, 2], 
              [3, 2]])

print(a.dot(b))

[[ 6  6]
 [12 14]]
